Add new method to match new ActiveRecord interface
With the upgrade to Rails 5.2.8.1 tests started failing with errors like:

```
Failure/Error: find_by_sql(sql).to_set

     NameError:
       undefined local variable or method `attribute_types' for AcademicCareerSource:Class
```

This method is supposed to return something that responds to
`#each_key`. I've added an OpenStruct that does that and the tests all
now pass again.